In [1]:
import numpy as np

In [2]:
data = np.load("./public_data/bmvs_bear/cameras_sphere.npz")

In [3]:
print(data.files)

['scale_mat_0', 'world_mat_0', 'scale_mat_1', 'world_mat_1', 'scale_mat_2', 'world_mat_2', 'scale_mat_3', 'world_mat_3', 'scale_mat_4', 'world_mat_4', 'scale_mat_5', 'world_mat_5', 'scale_mat_6', 'world_mat_6', 'scale_mat_7', 'world_mat_7', 'scale_mat_8', 'world_mat_8', 'scale_mat_9', 'world_mat_9', 'scale_mat_10', 'world_mat_10', 'scale_mat_11', 'world_mat_11', 'scale_mat_12', 'world_mat_12', 'scale_mat_13', 'world_mat_13', 'scale_mat_14', 'world_mat_14', 'scale_mat_15', 'world_mat_15', 'scale_mat_16', 'world_mat_16', 'scale_mat_17', 'world_mat_17', 'scale_mat_18', 'world_mat_18', 'scale_mat_19', 'world_mat_19', 'scale_mat_20', 'world_mat_20', 'scale_mat_21', 'world_mat_21', 'scale_mat_22', 'world_mat_22', 'scale_mat_23', 'world_mat_23', 'scale_mat_24', 'world_mat_24', 'scale_mat_25', 'world_mat_25', 'scale_mat_26', 'world_mat_26', 'scale_mat_27', 'world_mat_27', 'scale_mat_28', 'world_mat_28', 'scale_mat_29', 'world_mat_29', 'scale_mat_30', 'world_mat_30', 'scale_mat_31', 'world_mat_

In [4]:
print("world_mat_0:\n", data['world_mat_0'])

world_mat_0:
 [[-1.0889766e+02  3.2340955e+02  6.2724188e+02 -1.6156446e+04]
 [-4.8021997e+02 -3.6971255e+02  2.8318774e+02 -8.9503633e+03]
 [ 2.4123600e-01 -4.2752099e-01  8.7122399e-01 -2.1731400e+01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]


In [5]:
print("scale_mat_0:\n", data['scale_mat_0'])

scale_mat_0:
 [[ 1.6737139  0.         0.        -2.702419 ]
 [ 0.         1.6737139  0.        -1.3968586]
 [ 0.         0.         1.6737139 27.347609 ]
 [ 0.         0.         0.         1.       ]]
